#!/usr/bin/env ruby
# frozen_string_literal: true

# Refreshes _data/releases.yml from the GitHub Releases API.
#
#   ruby script/fetch-releases.rb
#
# Run by .github/workflows/pages.yml before `jekyll build`, and safe to run by
# hand. Uses GITHUB_TOKEN when present (5000 req/h instead of 60).
#
# The result is COMMITTED, not gitignored: a local `jekyll serve` has to show
# real version numbers, and the very first deploy has to work before the
# workflow has ever run. CI regenerates it in the workspace and does not push
# it back — the committed copy is a floor, not a cache to keep in sync.
#
# A repo with no releases at all (lightbox, until it is tagged) is recorded
# with `tag: null` rather than dropped, so the template can say "no release
# yet" instead of rendering a hole. A transient API failure keeps whatever the
# committed file already had: a blip must never blank a version number.

require 'json'
require 'net/http'
require 'uri'
require 'yaml'

ROOT     = File.expand_path('..', __dir__)
PLUGINS  = YAML.load_file(File.join(ROOT, '_data', 'plugins.yml'))
OUT_PATH = File.join(ROOT, '_data', 'releases.yml')
TOKEN    = ENV['GITHUB_TOKEN'] || ENV['GH_TOKEN']

previous = File.exist?(OUT_PATH) ? (YAML.load_file(OUT_PATH) || {}) : {}
failures = []

def api_get(path)
  uri = URI("https://api.github.com#{path}")
  req = Net::HTTP::Get.new(uri)
  req['Accept']               = 'application/vnd.github+json'
  req['X-GitHub-Api-Version'] = '2022-11-28'
  req['User-Agent']           = 'expertZentrale-redmine-plugins-site'
  req['Authorization']        = "Bearer #{TOKEN}" if TOKEN && !TOKEN.empty?

  res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true, open_timeout: 10, read_timeout: 20) do |http|
    http.request(req)
  end

  case res
  when Net::HTTPSuccess  then [:ok, JSON.parse(res.body)]
  when Net::HTTPNotFound then [:none, nil]
  else                        [:error, "#{res.code} #{res.message}"]
  end
end

releases = {}

PLUGINS.each do |plugin|
  id   = plugin['id']
  repo = plugin['repo']
  status, payload = api_get("/repos/#{repo}/releases/latest")

  case status
  when :ok
    zip = payload.fetch('assets', []).find { |a| a['name'].to_s.end_with?('.zip') }
    tar = payload.fetch('assets', []).find { |a| a['name'].to_s.end_with?('.tar.gz') }

    releases[id] = {
      'tag'          => payload['tag_name'],
      'version'      => payload['tag_name'].to_s.sub(/\Av/, ''),
      'published_at' => payload['published_at'].to_s[0, 10],
      'html_url'     => payload['html_url'],
      'zip_url'      => zip && zip['browser_download_url'],
      'tar_url'      => tar && tar['browser_download_url']
    }
    warn "  #{id.ljust(9)} #{payload['tag_name']}"
  when :none
    releases[id] = {
      'tag' => nil, 'version' => nil, 'published_at' => nil,
      'html_url' => "https://github.com/#{repo}/releases",
      'zip_url' => nil, 'tar_url' => nil
    }
    warn "  #{id.ljust(9)} (no releases yet)"
  else
    failures << "#{repo}: #{payload}"
    releases[id] = previous[id] if previous.key?(id)
    warn "  #{id.ljust(9)} FAILED (#{payload}) — keeping committed value"
  end
end

File.write(OUT_PATH, <<~HEADER + releases.to_yaml.sub(/\A---\n/, ''))
  # GENERATED by script/fetch-releases.rb — do not edit by hand.
  # Refreshed on every Pages build and by a weekly cron; the committed copy is
  # what a local `jekyll serve` and the first deploy read.
HEADER

warn ''
if failures.empty?
  warn "wrote #{OUT_PATH}"
else
  warn "wrote #{OUT_PATH} with #{failures.size} failure(s):"
  failures.each { |f| warn "  - #{f}" }
  # Deliberately exit 0: stale-but-correct version numbers beat a failed
  # deploy. CI surfaces the warnings in the log.
end
