#!/usr/bin/env python3
"""Write _data/shots.yml with the real pixel dimensions of every built screenshot.

Without this the <img> needs a guessed height attribute, and the guess is
badly wrong for some captures — agile's sprints tab is 2880x634, a 4.5:1 strip,
against a board screenshot that is nearly square. A wrong height reserves the
wrong box and the page jumps when the image loads.

Run by tools/optimise-shots.sh; safe to run on its own.
"""
import pathlib, subprocess, sys

root  = pathlib.Path(__file__).resolve().parents[1]
shots = root / 'assets' / 'img' / 'shots'
out   = root / '_data' / 'shots.yml'

if not shots.is_dir():
    sys.exit('no assets/img/shots — run tools/optimise-shots.sh first')

lines = [
    '# GENERATED by tools/index-shots.py — do not edit by hand.',
    '# Real dimensions of the 1x WebP files, so every <img> reserves the right box.',
]
count = 0
for plugin_dir in sorted(p for p in shots.iterdir() if p.is_dir()):
    lines.append(f'{plugin_dir.name}:')
    for lang_dir in sorted(p for p in plugin_dir.iterdir() if p.is_dir()):
        lines.append(f'  {lang_dir.name}:')
        for img in sorted(lang_dir.glob('*.webp')):
            if img.stem.endswith('@2x'):
                continue
            dims = subprocess.run(['identify', '-format', '%w %h', str(img)],
                                  capture_output=True, text=True, check=True).stdout
            w, h = dims.split()
            lines.append(f'    {img.stem}: {{w: {w}, h: {h}}}')
            count += 1

out.write_text('\n'.join(lines) + '\n')
print(f'  indexed {count} screenshots -> {out.relative_to(root)}')
